services:
  fresco:
    image: 'ghcr.io/complexdatacollective/fresco:latest'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app/next-app
    restart: always
    ports:
      - 3000:3000
    networks:
      - fresco_network
    env_file:
      - .env

  postgres:
    env_file:
      - .env
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data:Z
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${POSTGRES_USER}']
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - fresco_network

volumes:
  postgres:

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  fresco_network:
